plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.143'
}

evaluationDependsOn(':protocol')

repositories {
    mavenCentral()
    maven { url = 'https://maven.neoforged.net/releases' }
}

dependencies {
    implementation project(':protocol')
    compileOnly 'org.spongepowered:mixin:0.8.5'
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            programArgument '--username=Dev'
        }
        server {
            server()
            programArgument '--nogui'
        }
        configureEach {
            logLevel = org.slf4j.event.Level.INFO
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

tasks.named('jar') {
    manifest {
        attributes 'MixinConfigs': 'pixcore.mixins.json'
    }
    from project(':protocol').sourceSets.main.output
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveBaseName = 'Pixcore-NeoForge'
}
